#!/usr/bin/env bash
set -euo pipefail

# 使い方:
#   GOOGLE_BOOKS_API_KEY=xxxx ./ci_pre_xcodebuild.sh

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# 出力先ディレクトリ
OUT_DIR="${PROJECT_ROOT}/PictureBookLendingAdminApp/PictureBookLendingInfrastructure/Sources/PictureBookLendingInfrastructure"
OUT_PATH="${OUT_DIR}/SecretsGenerated.swift"

# 環境変数から API キーを取得
KEY="${GOOGLE_BOOKS_API_KEY:-}"
if [[ -z "${KEY}" ]]; then
  echo "error: GOOGLE_BOOKS_API_KEY が設定されていません。" >&2
  exit 1
fi

# ディレクトリが存在することを確認
if [[ ! -d "${OUT_DIR}" ]]; then
  echo "error: 出力先ディレクトリが存在しません: ${OUT_DIR}" >&2
  exit 1
fi

# SecretsGenerated.swift を生成
cat > "${OUT_PATH}" <<SWIFT
// @generated by ci_pre_xcodebuild.sh. DO NOT EDIT.
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

import Foundation

/// API キーや機密情報を管理するファイル
public enum Secrets {
    /// Google Books API キー
    /// 設定方法はREADME.mdを参照
    public static let googleBooksAPIKey: String? = "${KEY}"
}
SWIFT

echo "SecretsGenerated.swift を生成しました: ${OUT_PATH}"