#!/usr/bin/env bash
set -euo pipefail

# 使い方:
#   GOOGLE_BOOKS_API_KEY=xxxx ./ci_pre_xcodebuild.sh
#
# 任意:
#   GOOGLE_SERVICE_INFO_PLIST に GoogleService-Info.plist の中身をそのまま入れておくと、
#   Firebase (Crashlytics) 用の設定ファイルを生成する。未設定ならスキップする。

# スクリプトのディレクトリを取得
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# 出力先ディレクトリ
OUT_DIR="${PROJECT_ROOT}/PictureBookLendingAdminApp/PictureBookLendingInfrastructure/Sources/PictureBookLendingInfrastructure"
OUT_PATH="${OUT_DIR}/SecretsGenerated.swift"

# 環境変数から API キーを取得
KEY="${GOOGLE_BOOKS_API_KEY:-}"
if [[ -z "${KEY}" ]]; then
  echo "error: GOOGLE_BOOKS_API_KEY が設定されていません。" >&2
  exit 1
fi

# ディレクトリが存在することを確認
if [[ ! -d "${OUT_DIR}" ]]; then
  echo "error: 出力先ディレクトリが存在しません: ${OUT_DIR}" >&2
  exit 1
fi

# SecretsGenerated.swift を生成
cat > "${OUT_PATH}" <<SWIFT
// @generated by ci_pre_xcodebuild.sh. DO NOT EDIT.
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

import Foundation

/// API キーや機密情報を管理するファイル
public enum Secrets {
    /// Google Books API キー
    /// 設定方法はREADME.mdを参照
    public static let googleBooksAPIKey: String? = "${KEY}"
}
SWIFT

echo "SecretsGenerated.swift を生成しました: ${OUT_PATH}"

# GoogleService-Info.plist を生成（Firebase Crashlytics 用）
# public repo のため plist はコミットしていない。
# Secret が未設定の環境（PR時の単体テスト等）ではスキップし、
# アプリ側のガードによりクラッシュ収集なしで動作する。
PLIST_CONTENT="${GOOGLE_SERVICE_INFO_PLIST:-}"
PLIST_PATH="${PROJECT_ROOT}/PictureBookLendingAdminApp/PictureBookLendingAdmin/GoogleService-Info.plist"
if [[ -z "${PLIST_CONTENT}" ]]; then
  echo "GOOGLE_SERVICE_INFO_PLIST が未設定のため GoogleService-Info.plist の生成をスキップします。"
else
  printf '%s\n' "${PLIST_CONTENT}" > "${PLIST_PATH}"
  echo "GoogleService-Info.plist を生成しました: ${PLIST_PATH}"
fi